USE WEEK5_COMPANY_DB;

-- ‘Newbenefits’ 프로젝트에 참여하는 모든 사원의 급여를 10% 올린 경우의 급여를 제시하라. (Fname, Lname, Increased_sal)
SELECT 	FNAME, LNAME, (SALARY * 1.1) AS INCREAED_SAL
FROM	EMPLOYEE, WORKS_ON, PROJECT
WHERE	SSN=ESSN AND PNO=PNUMBER AND PNAME = 'Newbenefits';

-- 급여가 30,000달러에서 40,000달러 사이에 있는 5번 부서의 모든 사원을 검색하라.
SELECT	FNAME, LNAME
FROM 	EMPLOYEE
WHERE	SALARY >= 30000 AND SALARY <= 40000 AND DNO = 5;

SELECT	FNAME, LNAME
FROM 	EMPLOYEE
WHERE	(SALARY BETWEEN 30000 AND 40000) AND DNO = 5;

-- 모든 사원을 1. 급여(높은 순서) 2. 생년월일(나이가 많은 순서)을 제시하라.
SELECT	FNAME, LNAME, SALARY
FROM	EMPLOYEE
ORDER BY SALARY DESC; -- 1.

SELECT	FNAME, LNAME, BDATE
FROM	EMPLOYEE
ORDER BY BDATE ASC; -- 2.

-- 상사가 없는 모든 사원의 이름(Fname, Lname)을 검색하라.
SELECT	FNAME, LNAME
FROM 	EMPLOYEE
WHERE	SUPER_SSN IS NULL;

-- 부양가족의 성별(Sex)과 사원의 성별이 같은 사원의 이름(Fname, Lname)을 검색하라.
SELECT	FNAME, LNAME
FROM 	DEPENDENT, EMPLOYEE
WHERE	SSN=ESSN AND EMPLOYEE.SEX=DEPENDENT.SEX;

SELECT	FNAME, LNAME
FROM	EMPLOYEE
WHERE	SSN IN (SELECT	ESSN
				FROM	DEPENDENT
                WHERE	EMPLOYEE.SEX=DEPENDENT.SEX);
SELECT	FNAME, LNAME
FROM	EMPLOYEE
WHERE	EXISTS (SELECT	*
				FROM	DEPENDENT
                WHERE	SSN=ESSN AND
						EMPLOYEE.SEX=DEPENDENT.SEX);

-- [***]부양가족이 없는 종업원들의 이름(Fname, Lname)을 검색하라. 
SELECT 	*
FROM	EMPLOYEE
WHERE	NOT EXISTS (SELECT	*
					FROM	DEPENDENT
                    WHERE	SSN=ESSN);

-- [***]프로젝트 번호 1,2,3에서 일하는 사원의 주민등록번호(Essn)를 검색하라.
SELECT	DISTINCT ESSN
FROM	WORKS_ON
WHERE	PNO IN (1,2,3);


-- 사원의 급여의 합, 최고 급여, 최저 급여, 평균 급여를 구하라.
SELECT 	SUM(SALARY)
FROM	EMPLOYEE;

SELECT 	MAX(SALARY)
FROM	EMPLOYEE;

SELECT 	MIN(SALARY)
FROM	EMPLOYEE;

SELECT 	AVG(SALARY)
FROM	EMPLOYEE;

-- 회사의 총 사원수를 제시하라.
SELECT 	COUNT(*)
FROM 	EMPLOYEE;

-- 각 부서에서 근무하는 사원의 수를 검색하라. (부서이름과 소속 사원수를 제시)
SELECT	DNAME, COUNT(*) AS EMP_NO
FROM	EMPLOYEE, DEPARTMENT
WHERE	DNO=DNUMBER
GROUP BY	DNO;


-- 각 부서에 대해서 부서이름, 부서에 소속된 사원의 수와 최고급여와 평균 급여를 구하라.
SELECT	DNAME, COUNT(*), MAX(SALARY), AVG(SALARY)
FROM	EMPLOYEE, DEPARTMENT
WHERE	DNO=DNUMBER
GROUP BY	DNO;


-- 프로젝트에 대해서 프로젝트 번호, 프로젝트 이름, 그 프로젝트에서 근무 하는 사원들의 수를 검색하라.
SELECT	PNUMBER, PNAME, COUNT(*) AS EMP_NUM
FROM	WORKS_ON, PROJECT
WHERE	PNO=PNUMBER
GROUP BY	PNUMBER;


-- 세 명 이상의 사원이 근무하는 프로젝트에 대해서 프로젝트 번호, 프로젝트 이름, 그 프로젝트에서 근무하는 사원들의 수를 검색하라.
SELECT	PNUMBER, PNAME, COUNT(*)
FROM	WORKS_ON, PROJECT
WHERE	PNO=PNUMBER
GROUP BY	PNUMBER
HAVING		COUNT(*)>=3;


-- 프로젝트에 대해서 프로젝트 번호, 프로젝트 이름, 5번 부서에 속하면서 프로젝트에서 근무하는 사원의 수를 검색하라.
SELECT	PNUMBER, PNAME, COUNT(*)
FROM	WORKS_ON, PROJECT, EMPLOYEE
WHERE	PNO=PNUMBER AND SSN=ESSN AND DNO=5
GROUP BY	PNUMBER;


-- 3명 이상의 사원이 근무하는 각 부서에 대해서 부서 번호와 40,000달러가 넘는 급여를 받는 사원의 ssn 및 salary를 검색하라.
SELECT	PNUMBER, PNAME, COUNT(*)
FROM	WORKS_ON, PROJECT
WHERE	PNO=PNUMBER
GROUP BY	PNUMBER
HAVING		COUNT(*)>=3;

SELECT	SSN, SALARY
FROM 	EMPLOYEE
WHERE	SALARY > 40000 AND
		DNO IN (SELECT	DNO
				FROM	EMPLOYEE
                GROUP BY	DNO
                HAVING		COUNT(*)>=3);
                
SELECT	DNO, COUNT(*)
FROM	EMPLOYEE
GROUP BY	DNO;

SELECT * FROM EMPLOYEE;