USE WEEK5_COMPANY_DB;

-- ‘Newbenefits’ 프로젝트에 참여하는 모든 사원의 급여를 10% 올린 경우의 급여를 제시하라. (Fname, Lname, Increased_sal)
SELECT 	FNAME, LNAME, (SALARY * 1.1) AS INCREAED_SAL
FROM	EMPLOYEE, WORKS_ON, PROJECT
WHERE	SSN=ESSN AND PNO=PNUMBER AND PNAME = 'Newbenefits';

-- 급여가 30,000달러에서 40,000달러 사이에 있는 5번 부서의 모든 사원을 검색하라.
SELECT	FNAME, LNAME
FROM 	EMPLOYEE
WHERE	SALARY >= 30000 AND SALARY <= 40000 AND DNO = 5;

SELECT	FNAME, LNAME
FROM 	EMPLOYEE
WHERE	(SALARY BETWEEN 30000 AND 40000) AND DNO = 5;